version: "3"
services:

#TRAEFIK
    traefik:
        image: traefik:1.7
        restart: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - "./config/traefik/traefik.toml:/etc/traefik/traefik.toml"
          - "./logs/:/logs/"
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "acme-json:/tmp/acme"
        container_name: traefik
        labels:
            traefik.frontend.rule: "Host:traefik.docker.localhost"
            traefik.port: 8090
            traefik.frontend.auth.basic.users: "aymeric:$$apr1$$272Pq9LQ$$sLxYcxdHBBOaL5l8MJisx/"

#DATABASE
    db:
      image: mariadb:10.3
      volumes:
        - "db-data:/var/lib/mysql"
        - "./config/database:/etc/mysql/conf.d"
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_USER=user
        - MYSQL_DATABASE=blog
        - MYSQL_PASSWORD=pwd
      labels:
        traefik.enable: false

    blogTech:
      image: wordpress:5.2.2
      volumes:
        - "tech_wp-content:/var/www/html/"
        - "./config/wordpress/tech/themes/:/var/www/html/wp-content/themes/"
        - "./config/wordpress/tech/plugins/:/var/www/html/wp-content/plugins/"
      environment:
        - WORDPRESS_DB_HOST=db
        - WORDPRESS_DB_USER=user
        - WORDPRESS_DB_NAME=blog
        - WORDPRESS_TABLE_PREFIX=TEC_
        - WORDPRESS_DB_PASSWORD=pwd
      labels:
        traefik.frontend.rule: "Host:tech.docker.localhost"
        traefik.backend: "blogTech"
        traefik.port: 80
        traefik.protocol: "http"

    blogPerso:
      image: wordpress:5.2.2
      volumes:
        - "./config/wordpress/perso/themes/:/var/www/html/wp-content/themes/"
        - "./config/wordpress/perso/plugins/:/var/www/html/wp-content/plugins/"
        - "perso_wp-content:/var/www/html/wp-content"
      environment:
        - WORDPRESS_DB_HOST=db
        - WORDPRESS_DB_USER=user
        - WORDPRESS_DB_NAME=blog
        - WORDPRESS_TABLE_PREFIX=PER_
        - WORDPRESS_DB_PASSWORD=pwd
      labels:
        traefik.frontend.rule: "Host:blog.docker.localhost"
        traefik.backend: "blogPerso"
        traefik.port: 80
        traefik.protocol: "http"
  
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
       # - bootstrap.memory_lock=true
       # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - esdata01:/usr/share/elasticsearch/data
      labels:
        traefik.enable: false


    logstash:
      image: docker.elastic.co/logstash/logstash:7.3.0
      volumes:
        - ./config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
        - ./config/logstash/pipeline:/usr/share/logstash/pipeline:ro
        - ./logs/:/work/
      environment:
        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      depends_on:
        - elasticsearch
      labels:
        traefik.enable: false

    kibana:
      image: docker.elastic.co/kibana/kibana:7.3.0
      volumes:
        - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      depends_on:
        - elasticsearch
      labels:
        traefik.frontend.rule: "Host:kibana.docker.localhost"
        traefik.backend: "kibana"
        traefik.port: 5601
        traefik.protocol: "http"

    cerebro:
      image: lmenezes/cerebro
      depends_on:
        - elasticsearch
      labels:
        traefik.frontend.rule: "Host:cerebro.docker.localhost"
        traefik.backend: "cerebro"
        traefik.port: 9000
        traefik.protocol: "http"

volumes:
  db-data:
  acme-json:
  perso_wp-content:
  tech_wp-content:    
  esdata01:
